# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0886c1dcf8671777d0cdb9c6c8ffef7b88542590ecfc7ca3db820e12655f9a71ca5335392056171ecd79aa848655ba005075b17486749d6cce59b08dbc9c2a60

test:
  secret_key_base: 3719b0ae65f35abec9b09e8cd766857d0942afecee88c698382dc9a0cc9602a46cdba050a69650a65574f0ec26098d77537dd7f55e71e112ed369a2ba8eabe07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
